### ISSUE TITLE
EventHelper::playerLeaves

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstStdlib2#144]
Seems useful?

```
abstract class PlayerLeavesCallback
	protected abstract function call(player which)

PlayerLeavesCallback _playerLeavesCallback
function playerLeaves(PlayerLeavesCallback cb)
	_playerLeavesCallback = cb
	let t = CreateTrigger()..addAction() ->
		_playerLeavesCallback.call(GetTriggerPlayer())
	for i = 0 to 23
		t.registerPlayerEvent(Player(i), EVENT_PLAYER_LEAVE)
```

**Comment by Frotty** [comment]
Maybe, but probably not on it's own, because if you do leave handling, you might as well combine it with other things like a list of players. I did it in Frentity https://github.com/Frotty/Frentity/blob/master/wurst/player/Players.wurst

because I think that might be out of the scope of the stdlib.
Also, you should use closure events.

**Comment by Frotty** [comment]
For now you can just use `EventListener.add(EVENT_PLAYER_LEAVE) ->`
Reopen/new ticket if you still want this in another form.
