### ISSUE TITLE
Why does UnitOrHeroDefinition.setNormalAbilities() use string rather int as parameter?

### ISSUE THREAD

**Issue by 4eNNightmare** [wurstscript/WurstStdlib2#149]
**Current:**
`setNormalAbilities("AInv")`

**How it should be:**
`setNormalAbilities('AInv')`
_or_
`setNormalAbilities(AbilityIds.inventory)`

should not?

**Comment by Frotty** [comment]
No, it should not, since you can specify multiple ids. In the object editor you will see the same string "A000,A001,A002" for a list of spells, buildings constructed, units sold, etc.
In wurst to wrap this nicely you should use `commaList` like so:
`setNormalAbilities(commaList(AbilityIds.inventory, AbilityIds.cripple, AbilityIds.frostArmor))
